### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by darthwalsh** [octan3/img-clipboard-dump#2]
I'd be interested to use this script, but without a software license like MIT I'm not sure it would be legal...

**Comment by octan3** [comment]
You are welcome. If you like, please let me know what you made of this script.

**Comment by darthwalsh** [comment]
I wrote my own version of the script that saves the file, copies the new path to the clipboard, sleeps for 20 seconds, then deletes the file. 

That way I can Win+Shift+S to take a screenshot, then Win+R + "png" to paste a file path into an upload dialog :)
